Create missing ~/.stack for alpine integration-tests.yml
The GitHub Action integration-tests.yml is failing with:

~~~
+ [[ --alpine == \-\-\a\l\p\i\n\e ]]
+ touch /home/runner/.stack/config.yaml
touch: cannot touch '/home/runner/.stack/config.yaml': No such file or directory
Error: Process completed with exit code 1.
~~~

This attempts to fix that by adding: `mkdir -p ~/.stack`